# Generated by Django 5.2.11 on 2026-02-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_remove_organization_organizatio_name_537540_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='organization',
            name='organizatio_name_354df0_idx',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='user',
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['name'], name='organizatio_name_537540_idx'),
        ),
    ]
