# Generated by Django 5.2.11 on 2026-02-26 06:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_organization_owner_alter_membership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='organization',
            name='organizatio_name_537540_idx',
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['name', 'owner'], name='organizatio_name_3c7620_idx'),
        ),
    ]
