# Generated by Django 5.2.11 on 2026-02-26 06:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_remove_organization_organizatio_name_537540_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='organization',
            name='organizatio_name_3c7620_idx',
        ),
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together={('name', 'owner')},
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['name'], name='organizatio_name_537540_idx'),
        ),
    ]
