# Generated by Django 6.0.2 on 2026-02-20 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_alter_organization_unique_together'),
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('chart_type', models.CharField(choices=[('bar', 'Bar'), ('line', 'Line'), ('pie', 'Pie'), ('table', 'Table')], max_length=20)),
                ('group_by_column', models.CharField(max_length=255)),
                ('metric_column', models.CharField(max_length=255)),
                ('aggregation', models.CharField(choices=[('sum', 'SUM'), ('avg', 'AVG'), ('count', 'COUNT'), ('min', 'MIN'), ('max', 'MAX')], max_length=20)),
                ('filters', models.JSONField(blank=True, null=True)),
                ('limit', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='organizations.organization')),
                ('saved_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='query.savedquery')),
            ],
        ),
    ]
